### ISSUE TITLE
Missing .jsii file

### ISSUE THREAD

**Issue by gkniesel** [aws-samples/llm-app-genie#27]
When I try to deploy a stack with cdk I get the following error on my MacBook Pro (Sonoma 14.2.1 ). Any idea?

(llm-app-genie-automation-py3.10) gk@NB 06_automation % cdk deploy GenieOpenSearchDomainStack GenieOpenSearchIngestionPipelineStack --require-approval never
jsii.errors.JavaScriptError: 
  @jsii/kernel.Fault: Error for package tarball /Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/asset_awscli_v1/_jsii/asset-awscli-v1@2.2.200.jsii.tgz: Expected to find .jsii file in /var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/jsii-kernel-eRKKiA/node_modules/@aws-cdk/asset-awscli-v1, but no such file found
      at Kernel._Kernel_load (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp6bwcblsu/lib/program.js:10033:23)
      at /private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp6bwcblsu/lib/program.js:9755:181
      at Kernel._Kernel_debugTime (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp6bwcblsu/lib/program.js:10467:24)
      at Kernel.load (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp6bwcblsu/lib/program.js:9755:96)
      at KernelHost.processRequest (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp6bwcblsu/lib/program.js:11691:36)
      at KernelHost.run (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp6bwcblsu/lib/program.js:11651:22)
      at /private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp6bwcblsu/lib/program.js:17533:10
      at Object.<anonymous> (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp6bwcblsu/lib/program.js:17534:3)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gk/code/demeter/aws/llm-app-genie/06_automation/app.py", line 7, in <module>
    from aws_cdk import App, Environment, Tags
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/__init__.py", line 1422, in <module>
    from ._jsii import *
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/_jsii/__init__.py", line 13, in <module>
    import aws_cdk.asset_awscli_v1._jsii
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/asset_awscli_v1/_jsii/__init__.py", line 13, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load(
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/jsii/_runtime.py", line 55, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/jsii/_kernel/__init__.py", line 299, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 354, in load
    return self._process.send(request, LoadResponse)
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 341, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Error for package tarball /Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/asset_awscli_v1/_jsii/asset-awscli-v1@2.2.200.jsii.tgz: Expected to find .jsii file in /var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/jsii-kernel-eRKKiA/node_modules/@aws-cdk/asset-awscli-v1, but no such file found

Subprocess exited with error 1

**Comment by mimuta** [comment]
Hi Guido, can you check the CDK and AWS cli versions?

**Comment by gkniesel** [comment]
Yes, sure, here is the output:

cdk --version
2.117.0 (build 59d9b23)

aws --version
aws-cli/2.13.34 Python/3.11.6 Darwin/23.2.0 exe/x86_64 prompt/off

**Comment by mimuta** [comment]
Ok, just to make sure do you have silicon (M1,2) or Intel Macbook? Your cli version looks like Intel.

You versions are good and up to date, so should be something wrong with packages.

**Comment by gkniesel** [comment]
Yes, 2.3 GHz 8-Core Intel Core i9

I have already completely uninstalled and reinstalled everything twice (Node, aws-cdk, python, poetry) but the error persists.

**Comment by gkniesel** [comment]
I tried it again, but i doesn’t help:

gk@NB 06_automation % curl -sSL https://install.python-poetry.org | python3 - --uninstall
Removing Poetry (1.7.1)
gk@NB 06_automation % rm -r /Users/gk/Library/Caches/pypoetry
gk@NB 06_automation % curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/Users/gk/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.7.1): Done

Poetry (1.7.1) is installed now. Great!

You can test that everything is set up by executing:

`poetry --version`

gk@NB 06_automation % poetry install
Creating virtualenv llm-app-genie-automation-YfMcj_Y_-py3.10 in /Users/gk/Library/Caches/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 22 installs, 0 updates, 0 removals

  • Installing attrs (23.1.0)
  • Installing exceptiongroup (1.1.3)
  • Installing six (1.16.0)
  • Installing typing-extensions (4.8.0)
  • Installing cattrs (23.1.2)
  • Installing importlib-resources (6.1.0)
  • Installing publication (0.0.3)
  • Installing python-dateutil (2.8.2)
  • Installing typeguard (2.13.3)
  • Installing jmespath (1.0.1)
  • Installing jsii (1.90.0)
  • Installing urllib3 (2.0.6)
  • Installing aws-cdk-asset-awscli-v1 (2.2.200)
  • Installing aws-cdk-asset-kubectl-v20 (2.1.2)
  • Installing aws-cdk-asset-node-proxy-agent-v6 (2.0.1)
  • Installing botocore (1.31.62)
  • Installing constructs (10.3.0)
  • Installing aws-cdk-lib (2.100.0)
  • Installing s3transfer (0.7.0)
  • Installing aws-cdk-aws-lambda-python-alpha (2.100.0a0)
  • Installing boto3 (1.28.62)
  • Installing cdk-nag (2.27.158)

Installing the current project: llm-app-genie-automation (1.0.3)
gk@NB 06_automation % poetry shell
Spawning shell within /Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10
gk@NB 06_automation % emulate bash -c '. /Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/bin/activate'
(llm-app-genie-automation-py3.10) gk@NB 06_automation % cdk deploy GenieOpenSearchIngestionPipelineStack --require-approval never 
jsii.errors.JavaScriptError: 
  @jsii/kernel.Fault: Error for package tarball /Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/asset_awscli_v1/_jsii/asset-awscli-v1@2.2.200.jsii.tgz: Expected to find .jsii file in /var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/jsii-kernel-3gg62F/node_modules/@aws-cdk/asset-awscli-v1, but no such file found
      at Kernel._Kernel_load (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp3o2d91vm/lib/program.js:10033:23)
      at /private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp3o2d91vm/lib/program.js:9755:181
      at Kernel._Kernel_debugTime (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp3o2d91vm/lib/program.js:10467:24)
      at Kernel.load (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp3o2d91vm/lib/program.js:9755:96)
      at KernelHost.processRequest (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp3o2d91vm/lib/program.js:11691:36)
      at KernelHost.run (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp3o2d91vm/lib/program.js:11651:22)
      at /private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp3o2d91vm/lib/program.js:17533:10
      at Object.<anonymous> (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmp3o2d91vm/lib/program.js:17534:3)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gk/code/demeter/aws/llm-app-genie/06_automation/app.py", line 7, in <module>
    from aws_cdk import App, Environment, Tags
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/__init__.py", line 1422, in <module>
    from ._jsii import *
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/_jsii/__init__.py", line 13, in <module>
    import aws_cdk.asset_awscli_v1._jsii
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/asset_awscli_v1/_jsii/__init__.py", line 13, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load(
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/jsii/_runtime.py", line 55, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/jsii/_kernel/__init__.py", line 299, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 354, in load
    return self._process.send(request, LoadResponse)
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 341, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Error for package tarball /Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/asset_awscli_v1/_jsii/asset-awscli-v1@2.2.200.jsii.tgz: Expected to find .jsii file in /var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/jsii-kernel-3gg62F/node_modules/@aws-cdk/asset-awscli-v1, but no such file found

Subprocess exited with error 1
(llm-app-genie-automation-py3.10) gk@NB 06_automation %

**Comment by mimuta** [comment]
Can you check if the file "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y-py3.10/lib/python3.10/site-packages/aws_cdk/asset_awscli_v1/_jsii/asset-awscli-v1@2.2.200.jsii.tgz" exists in your local folder, I see in in my local folder.

If not, try to delete the virtual environment folder and poetry.lock file in 06_automation and redo poetry install.

**Comment by gkniesel** [comment]
I cannot find the  file asset-awscli-v1@2.2.200.jsii.tgz in this folder, but instead I find the file asset-kubectl-v20@2.1.2.jsii.tgz. 

I have run the cdk command again and the error message has changed slightly. The tar file asset-kubectl-v20@2.1.2.jsii.tgz is now used. 

Maybe the reason for this change is that I have executed what you recommended in your previous message.

Here is the new error message:

gk@NB 06_automation % emulate bash -c '. /Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/bin/activate'
(llm-app-genie-automation-py3.10) gk@NB 06_automation % cdk deploy GenieOpenSearchIngestionPipelineStack --require-approval never
jsii.errors.JavaScriptError: 
  @jsii/kernel.Fault: Error for package tarball /Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/asset_kubectl_v20/_jsii/asset-kubectl-v20@2.1.2.jsii.tgz: Expected to find .jsii file in /var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/jsii-kernel-UUbWoy/node_modules/@aws-cdk/asset-kubectl-v20, but no such file found
      at Kernel._Kernel_load (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmpmq7faorx/lib/program.js:10037:23)
      at /private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmpmq7faorx/lib/program.js:9759:181
      at Kernel._Kernel_debugTime (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmpmq7faorx/lib/program.js:10471:24)
      at Kernel.load (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmpmq7faorx/lib/program.js:9759:96)
      at KernelHost.processRequest (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmpmq7faorx/lib/program.js:11699:36)
      at KernelHost.run (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmpmq7faorx/lib/program.js:11659:22)
      at Immediate._onImmediate (/private/var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/tmpmq7faorx/lib/program.js:11660:46)
      at process.processImmediate (node:internal/timers:476:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gk/code/demeter/aws/llm-app-genie/06_automation/app.py", line 7, in <module>
    from aws_cdk import App, Environment, Tags
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/__init__.py", line 1508, in <module>
    from ._jsii import *
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/_jsii/__init__.py", line 14, in <module>
    import aws_cdk.asset_kubectl_v20._jsii
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/asset_kubectl_v20/_jsii/__init__.py", line 13, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load(
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/jsii/_runtime.py", line 55, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/jsii/_kernel/__init__.py", line 299, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 354, in load
    return self._process.send(request, LoadResponse)
  File "/Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 341, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Error for package tarball /Users/gk/Library/Caches/pypoetry/virtualenvs/llm-app-genie-automation-YfMcj_Y_-py3.10/lib/python3.10/site-packages/aws_cdk/asset_kubectl_v20/_jsii/asset-kubectl-v20@2.1.2.jsii.tgz: Expected to find .jsii file in /var/folders/sn/56x6rh457l56m3tqcgbprck80000gn/T/jsii-kernel-UUbWoy/node_modules/@aws-cdk/asset-kubectl-v20, but no such file found

Subprocess exited with error 1

**Comment by mimuta** [comment]
This is still strange, as files keep missing, did you remove the files from the disk (/Users/[username]/Library/Caches/pypoetry/virtualenvs/)?

Can you try some other cdk commands, like:

cdk synth
cdk ls

Also, please make sure docker is running, it will be needed for deployment, but error is not for it anyway.
